# LED net tables for render.s (generated by stage4/experiments/gen_led.py).
# Facelet i (U, L, F, R, B, D faces, 4 each, row-major) shows the sticker in slot
# led_slot[i] of corner position led_pos[i] (0-6 = movable positions, 7 = fixed UFL);
# its first LED is at LED_MATRIX_0_BASE + led_off[i] (35 x 25 matrix, 4 x 3 LEDs per facelet).
.data
led_pos:  .byte 6, 3, 7, 0, 6, 7, 5, 2, 7, 0, 2, 1, 0, 3, 1, 4, 3, 6, 4, 5, 2, 1, 5, 4
led_slot: .byte 0, 0, 0, 0, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 0, 0, 0, 0
# led_home[c*4 + j] = face (0 U, 1 L, 2 F, 3 R, 4 B, 5 D) of sticker j of corner c when solved
led_home: .byte 0, 3, 2, 0, 5, 2, 3, 0, 5, 1, 2, 0, 0, 4, 3, 0, 5, 3, 4, 0, 5, 4, 1, 0, 0, 1, 4, 0, 0, 2, 1, 0
led_rgb:  .word 0xFFFFFF, 0xFF8000, 0x00C000, 0xFF0000, 0x0050FF, 0xFFFF00
led_off:  .half 36, 52, 456, 472, 980, 996, 1400, 1416, 1016, 1032, 1436, 1452, 1052, 1068, 1472, 1488, 1088, 1104, 1508, 1524, 1996, 2012, 2416, 2432
# quarter-turn tables, same as solver.c source/twist, padded to 8 per face
led_src:  .byte 1,4,2,0,3,5,6,7, 0,1,2,4,5,6,3,7, 0,2,5,3,1,4,6,7
led_tw:   .byte 1,2,0,2,1,0,0,0, 0,0,0,1,2,1,2,0, 0,0,0,0,0,0,0,0
# working copy of the cube: corner and twist at each position (7 = fixed corner)
led_p:    .byte 0,0,0,0,0,0,0,7
led_o:    .byte 0,0,0,0,0,0,0,0
led_tp:   .byte 0,0,0,0,0,0,0,7
led_to:   .byte 0,0,0,0,0,0,0,0
.text
